//
//  ClipboardMonitor.swift
//  MiniMe
//

import AppKit

/// Watches the pasteboard and records changes into a `ClipboardStore`.
///
/// macOS has no clipboard-change notification, so this polls `changeCount`.
/// The pasteboard is injectable so tests can drive a private one.
@MainActor
final class ClipboardMonitor: ObservableObject {

    static let pollInterval: TimeInterval = 0.5
    static let maxImageBytes = 25 * 1024 * 1024

    /// Markers apps use to say "do not persist this" — password managers and
    /// password generators set these.
    private static let sensitiveTypes: Set<NSPasteboard.PasteboardType> = [
        NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"),
        NSPasteboard.PasteboardType("org.nspasteboard.TransientType"),
        NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")
    ]

    var captureImagesAndFiles = true
    var ignoreConcealed = true

    private let store: ClipboardStore
    private let pasteboard: NSPasteboard
    private var timer: Timer?
    private var lastChangeCount: Int

    init(store: ClipboardStore, pasteboard: NSPasteboard = .general) {
        self.store = store
        self.pasteboard = pasteboard
        self.lastChangeCount = pasteboard.changeCount
    }

    // MARK: - Lifecycle

    func start() {
        stop()
        lastChangeCount = pasteboard.changeCount
        timer = Timer.scheduledTimer(withTimeInterval: Self.pollInterval, repeats: true) { [weak self] _ in
            Task { @MainActor [weak self] in self?.poll() }
        }
    }

    func stop() {
        timer?.invalidate()
        timer = nil
    }

    /// Marks the current pasteboard state as already seen, so a write MiniMe made
    /// itself (picking an entry, or the OCR auto-copy) is not re-ingested.
    func acknowledgeSelfWrite() {
        lastChangeCount = pasteboard.changeCount
    }

    // MARK: - Polling

    func poll() {
        let changeCount = pasteboard.changeCount
        guard changeCount != lastChangeCount else { return }
        lastChangeCount = changeCount
        capture()
    }

    private func capture() {
        if ignoreConcealed, let types = pasteboard.types,
           types.contains(where: { Self.sensitiveTypes.contains($0) }) {
            return
        }

        guard let content = readContent() else { return }

        let app = NSWorkspace.shared.frontmostApplication
        let entry = ClipboardEntry(
            content: content,
            sourceAppName: app?.localizedName,
            sourceAppBundleID: app?.bundleIdentifier
        )

        let stored = store.add(entry)
        generateThumbnail(for: stored)
    }

    /// Reads files, then images, then text. Order matters: a Finder file copy also
    /// places a text representation on the pasteboard, so reading text first would
    /// misclassify every file copy.
    private func readContent() -> ClipboardContent? {
        if captureImagesAndFiles {
            if let urls = pasteboard.readObjects(
                forClasses: [NSURL.self],
                options: [.urlReadingFileURLsOnly: true]
            ) as? [URL], !urls.isEmpty {
                return .files(paths: urls.map(\.path))
            }

            if let images = pasteboard.readObjects(forClasses: [NSImage.self], options: nil) as? [NSImage],
               let image = images.first {
                // An image was on the pasteboard: either store it or record
                // nothing. Never fall through to the text representation.
                return imageContent(from: image)
            }
        }

        guard let string = pasteboard.string(forType: .string),
              !string.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty else { return nil }
        return .text(string)
    }

    private func imageContent(from image: NSImage) -> ClipboardContent? {
        guard let data = ClipboardThumbnailer.fullSizePNGData(from: image) else { return nil }
        // A single very large copy should not dominate the store.
        guard data.count <= Self.maxImageBytes else { return nil }

        let fileName = "\(UUID().uuidString).png"
        guard store.writeBlob(data, named: fileName) else { return nil }

        // Measured from the encoded blob, not from `image.size`. NSImage.size is in
        // POINTS, so a Retina capture would report half its real resolution and the
        // title would read "Image 1440×900" for a 2880×1800 file.
        let rep = NSBitmapImageRep(data: data)

        return .image(
            fileName: fileName,
            pixelWidth: rep?.pixelsWide ?? Int(image.size.width.rounded()),
            pixelHeight: rep?.pixelsHigh ?? Int(image.size.height.rounded())
        )
    }

    // MARK: - Thumbnails

    /// Generated eagerly and asynchronously: the entry is already in the store, so
    /// the picker never blocks, and the sandbox's read grant on pasteboard file
    /// URLs is still live at this point.
    private func generateThumbnail(for entry: ClipboardEntry) {
        let thumbnailName = "\(entry.id.uuidString)-thumb.png"

        switch entry.content {
        case .text:
            return

        case .image(let fileName, _, _):
            let source = store.blobURL(named: fileName)
            Task { @MainActor in
                guard let image = NSImage(contentsOf: source),
                      let data = ClipboardThumbnailer.pngData(
                        from: image,
                        fitting: ClipboardThumbnailer.maxDimension
                      ) else { return }
                if store.writeBlob(data, named: thumbnailName) {
                    store.setThumbnail(thumbnailName, forEntry: entry.id)
                }
            }

        case .files(let paths):
            guard let first = paths.first else { return }
            let url = URL(fileURLWithPath: first)
            Task { @MainActor in
                guard let data = await ClipboardThumbnailer.fileThumbnailData(for: url) else { return }
                if store.writeBlob(data, named: thumbnailName) {
                    store.setThumbnail(thumbnailName, forEntry: entry.id)
                }
            }
        }
    }
}
